version: "3.9"

services:
  db:
    image: postgres:16
    container_name: fyp_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: fyp
      POSTGRES_USER: fyp_user
      POSTGRES_PASSWORD: fyp_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
